#
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd at denx.de.
# (C) Copyright 2010, Thomas Chou <thomas at wytron.com.tw>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= socfpga.o
